blog/urls.py
from django.urls.conf import path, include

from blog.views.blog_likes_dislikes_views import *
from blog.views.blog_views import *
from blog.views.comment_likes_dislikes_views import *
from blog.views.comment_views import *
from blog.views.pin_comment_views import *
from blog.views.reply_views import *
from blog.views.tags_views import *
from blog.views.user_views import *


app_name="blog"

urlpatterns = [
    path('login', login_form, name="login"),
    path('signout', signout_form, name="signout"),
    path('', get_users, name="get_users"),
    path('signup', signup, name="signup"),

    # dashboard paths
    path('dashboard/', include('blog.dashboard_urls'), name="dashboard"),

    # blog access
    path('<int:blog>', get_blog, name="get_blog"),
    path('<int:user>/blogs', get_blogs, name="get_blogs"),

    # blog likes, dislikes
    path('<int:blogid>/like', set_like, name="set_like"),
    path('<int:blogid>/dislike', set_dislike, name="set_dislike"),

    # comment likes, dislikes
    path('<int:commentid>/like/comment', set_comment_like, name="set_comment_like"),
    path('<int:commentid>/dislike/comment', set_comment_dislike, name="set_comment_dislike"),

    # blog 
    path('create_blog', create_blog, name="create_blog"),
    path('update/<int:blogid>', update_blog, name="update_blog"),
    path('delete/<int:blogid>', delete_blog, name="delete_blog"),


    # tag 
    path('create_tag', create_tag, name="create_tag"),
    path('<int:tagid>/update/tag', update_tag, name="update_tag"),
    path('<int:tagid>/delete/tag', delete_tag, name="delete_tag"),


    # comments
    path('<int:blogid>/add/comment', add_comment, name="add_comment"),
    path('<int:blogid>/<int:commentid>/update/comment', update_comment, name="update_comment"),
    path('<int:blogid>/<int:commentid>/delete/comment', delete_comment, name="delete_comment"),

    # pin comment
    path('<int:commentid>/pin/comment', pin_comment, name="pin_comment"),

    # reply comments
    path('<int:blogid>/<int:commentid>/reply/comment', create_reply_comment, name="add_reply"),
    path('<int:blogid>/<int:commentid>/<int:reply_commentid>/update/reply/comment', update_reply_comment, name="update_reply"),
    path('<int:blogid>/<int:commentid>/<int:reply_commentid>/delete/reply/comment', delete_reply_comment, name="delete_reply"),


]

blogsite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('blog.urls'))
]

blog/views/bld_per_user_views.py
from django.http.response import  HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from blog.models import Blog

def blog_likes_per_user(req):
    
    if req.user.is_authenticated:

        blog_likes_by_user = Blog.objects.filter(liked_users__id=req.user.id)

        return render(req, 'blog/get_blog_likes_per_user.html', {'blog_likes': blog_likes_by_user})

    else:
        next = req.GET.get('next', '/')
        return HttpResponseRedirect(reverse('blog:login') + "?next=" + next)



def blog_dislikes_per_user(req):
    if req.user.is_authenticated:

        blog_dislikes_by_user = Blog.objects.filter(disliked_users__id=req.user.id)

        return render(req, 'blog/get_blog_dislikes_per_user.html', {'blog_dislikes': blog_dislikes_by_user})

    else:
        next = req.GET.get('next', '/')
        return HttpResponseRedirect(reverse('blog:login') + "?next=" + next)

blog/views/blog_likes_dislikes_views.py
from django.http.response import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse


from blog.models import Blog

def set_like(req, blogid):
    try:

        if req.user.is_authenticated:

            blog = get_object_or_404(Blog, pk=blogid)


            if blog.liked_users.filter(id=req.user.id).count() == 0:
                blog.liked_users.add(req.user)
                blog.noOfLikes += 1

                if blog.disliked_users.filter(id=req.user.id).count():
                    blog.disliked_users.remove(req.user)
                    blog.noOfDisLikes -= 1
            else:    
                blog.liked_users.remove(req.user)
                blog.noOfLikes -= 1


            blog.save()


            return HttpResponseRedirect(reverse('blog:get_blog', kwargs={'blog': blogid}) + "?next=0")
        else:
            next = req.GET.get('next', '/')
            return HttpResponseRedirect(reverse('blog:login') + "?next=" + next)
    except Blog.DoesNotExist:
        raise Http404("The blog doesn't exists.")



def set_dislike(req, blogid):
    try:

        if req.user.is_authenticated:

            blog = get_object_or_404(Blog, pk=blogid)

            if blog.disliked_users.filter(id=req.user.id).count() == 0:
                blog.disliked_users.add(req.user)
                blog.noOfDisLikes += 1

                if blog.liked_users.filter(id=req.user.id).count():
                    blog.liked_users.remove(req.user)
                    blog.noOfLikes -= 1
            else:    
                blog.disliked_users.remove(req.user)
                blog.noOfDisLikes -= 1
                        
            blog.save()


            return HttpResponseRedirect(reverse('blog:get_blog', kwargs={'blog': blogid}) + "?next=0")
        else:
            next = req.GET.get('next', '/')
            return HttpResponseRedirect(reverse('blog:login') + "?next=" + next)
    except Blog.DoesNotExist:
        raise Http404("The blog doesn't exists.")

blog/views/blog_views.py
from django.http.response import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.urls import reverse


from blog.forms import BlogForm, DisabledBlogForm

from blog.models import Blog, Comment, Tags

def create_blog(req):
    if req.user.is_authenticated:

        if req.method == "POST":

            form = BlogForm(req.POST)

            if form.is_valid():


                print(form.cleaned_data['tags'])

                blog = form.save(commit=False)
                blog.user = req.user
                blog.modified_timestamp=now()
                blog.save()

                tags = form.cleaned_data['tags']
                noOfTags = 0

                for tag in tags:
                    blog.tags.add(Tags.objects.get(tag_name=tag))
                    noOfTags += 1

                

                blog.noOfTags = noOfTags
                blog.save()

                return HttpResponseRedirect(reverse('blog:dashboard_home'))

        else:
            form = BlogForm()

        return render(req, 'blog/create_blog.html', {'form': form})

    else:
        return HttpResponseRedirect(reverse('blog:login'))


def get_blogs(req, user):
    
    userO = get_object_or_404(User, pk=user)
    blogs = Blog.objects.filter(user=userO, isVisible=True)
    

    return render(req, 'blog/blog_list.html', {'blogs': blogs})


def get_comment_section(comments, auth_user, root_comment_id=-1):
    comment_section = []

    # go through all the comments
    for comment in comments:

        liked = False
        disliked = False

        # find out whether the comment is liked or not by the auth user
        if auth_user and comment.liked_users.filter(id=auth_user.id).count() > 0:
            liked = True
        elif auth_user and comment.disliked_users.filter(id=auth_user.id).count() > 0:
            disliked = True

        comment_replies = {
            'comment': comment,
            'replies': [],
            'root_comment_id': (root_comment_id if root_comment_id != -1 else comment.comment_id),
            'liked': liked,
            'disliked': disliked
        }

        pinned_comments = Comment.objects.filter(head_comment=comment, is_pinned=True).order_by('-pinned_timestamp')
        unpinned_comment = Comment.objects.filter(head_comment=comment, is_pinned=False).order_by('-modified_timestamp')

        sub_comments = list(pinned_comments) + list(unpinned_comment)

        comment_replies['replies'] = get_comment_section(sub_comments, auth_user, comment.comment_id)

        comment_section.append(comment_replies)

    return comment_section

        

def get_blog(req, blog):

    try:
        blog = Blog.objects.get(pk=blog)

        if req.GET.get('next', '/') == '/':
            blog.numberOfViews += 1


        liked = False
        disLiked = False
        user = None

        if req.user.is_authenticated:

            # get Likes per User obj
            if blog.liked_users.filter(id=req.user.id).count():
                liked = True
            elif blog.disliked_users.filter(id=req.user.id).count():
                disLiked = True

            user = req.user

        
        pinned_comments = Comment.objects.filter(blog=blog, isRoot=True, is_pinned=True).order_by('-pinned_timestamp')
        unpinned_comment = Comment.objects.filter(blog=blog, isRoot=True, is_pinned=False).order_by('-modified_timestamp')

        comments = list(pinned_comments) + list(unpinned_comment)

        comment_section = get_comment_section(comments=comments, auth_user=user)


        blog.save()

        
        return render(req, 'blog/get_blog.html', {'blog': blog, 'liked': liked, 'disLiked': disLiked, 'comments': comment_section})
    except Blog.DoesNotExist:
        raise Http404("The blog doesn't exists.")



def update_blog(req, blogid):
    if req.user.is_authenticated:

        blog = get_object_or_404(Blog, pk=blogid)

        if req.method == 'POST':

            form = BlogForm(req.POST)

            if form.is_valid():
                
                blog.title = form.cleaned_data['title']
                blog.body = form.cleaned_data['body']
                blog.isVisible = form.cleaned_data['isVisible']
                blog.modified_timestamp = now()

                # update the tags
                # empty the tags 
                blog.tags.clear()

                blog.save()


                tags = form.cleaned_data['tags']
                noOfTags = 0

                for tag in tags:
                    blog.tags.add(Tags.objects.get(tag_name=tag))
                    noOfTags += 1

                
                blog.noOfTags = noOfTags
                blog.save()


                return HttpResponseRedirect(reverse('blog:dashboard_home'))

        else:
            form = BlogForm(instance=blog)

        return render(req, 'blog/update_blog.html', {'form': form, 'blogid': blogid})

    return HttpResponseRedirect(reverse('blog:login'))
                        
                        
def delete_blog(req, blogid):
    if req.user.is_authenticated:

        blog = get_object_or_404(Blog, pk=blogid)

        if req.method == 'POST':
            form = DisabledBlogForm(req.POST)
            Blog.objects.filter(pk=blogid).delete()
            return HttpResponseRedirect(reverse('blog:dashboard_home'))

        else:
            form = DisabledBlogForm(instance=blog)

        return render(req, 'blog/delete_blog.html', {'form': form, 'blogid': blogid})


    return HttpResponseRedirect(reverse('blog:login'))

blog/views/cld_per_user_views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from blog.models import Comment

def comment_likes_per_user(req):
    if req.user.is_authenticated:

        comment_likes_by_user = Comment.objects.filter(liked_users__id=req.user.id)

        return render(req, 'blog/get_comment_likes_per_user.html', {'comment_likes': comment_likes_by_user})

    else:
        next = req.GET.get('next', '/')
        return HttpResponseRedirect(reverse('blog:login') + "?next=" + next)
    
def comment_dislikes_per_user(req):
    if req.user.is_authenticated:

        comment_dislikes_by_user = Comment.objects.filter(disliked_users__id=req.user.id)

        return render(req, 'blog/get_comment_dislikes_per_user.html', {'comment_dislikes': comment_dislikes_by_user})

    else:
        next = req.GET.get('next', '/')
        return HttpResponseRedirect(reverse('blog:login') + "?next=" + next)

blog/views/comment_likes_dislikes_views.py
from django.http.response import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse

from blog.models import Blog, Comment


# comment likes, dislikes
def set_comment_like(req, commentid):
    try:

        if req.user.is_authenticated:

            comment = get_object_or_404(Comment, pk=commentid)

            if comment.liked_users.filter(id=req.user.id).count():
                comment.noOfLikes -= 1
                comment.liked_users.remove(req.user)
            else:
                comment.noOfLikes += 1
                comment.liked_users.add(req.user)

                if comment.disliked_users.filter(id=req.user.id).count():
                    comment.noOfDisLikes -= 1
                    comment.disliked_users.remove(req.user)            
                        
            comment.save()


            next = req.GET.get('next', '/')

            if next != '/':
                return HttpResponseRedirect(next)
            else:
                return HttpResponseRedirect(reverse('blog:get_blog', kwargs={'blog': comment.blog.blogid}) + "?next=0")
        else:
            next = req.GET.get('next', '/')
            return HttpResponseRedirect(reverse('blog:login') + "?next=" + next)
    except Blog.DoesNotExist:
        raise Http404("The blog doesn't exists.")
        



def set_comment_dislike(req, commentid):
    try:

        if req.user.is_authenticated:

            comment = get_object_or_404(Comment, pk=commentid)


            if comment.disliked_users.filter(id=req.user.id).count():
                comment.noOfDisLikes -= 1
                comment.disliked_users.remove(req.user)
            else:
                comment.noOfDisLikes += 1
                comment.disliked_users.add(req.user)

                if comment.liked_users.filter(id=req.user.id).count():
                    comment.noOfLikes -= 1
                    comment.liked_users.remove(req.user)            
                        
            
            comment.save()


            next = req.GET.get('next', '/')

            if next != '/':
                return HttpResponseRedirect(next)
            else:
                return HttpResponseRedirect(reverse('blog:get_blog', kwargs={'blog': comment.blog.blogid}) + "?next=0")
        else:
            next = req.GET.get('next', '/')
            return HttpResponseRedirect(reverse('blog:login') + "?next=" + next)
    except Blog.DoesNotExist:
        raise Http404("The blog doesn't exists.")

blog/views/comments_per_user_views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from blog.models import UserAnalytics

def comments_given_per_user(req):
    if req.user.is_authenticated:

        user = UserAnalytics.objects.get(user=req.user)
        comments_given_by_user = user.comments_given.all()

        return render(req, 'blog/get_comments_given_per_user.html', {'comments_given': comments_given_by_user})

    else:
        next = req.GET.get('next', '/')
        return HttpResponseRedirect(reverse('blog:login') + "?next=" + next)

blog/views/pin_comment_views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.urls import reverse

from blog.models import Comment

def pin_comment(req, commentid):
    
    comment = get_object_or_404(Comment, pk=commentid)

    comment.is_pinned = not comment.is_pinned

    if comment.is_pinned:
        comment.pinned_timestamp = timezone.now()

    comment.save()

    next = req.GET.get('next', '/')

    if next != '/':
        return HttpResponseRedirect(next)
    else:
        return HttpResponseRedirect(reverse('blog:get_blog', kwargs={'blog': comment.blog.blogid}) + "?next=0")

blog/views/replies_per_user_views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from blog.models import UserAnalytics

def replies_given_per_user(req):
    if req.user.is_authenticated:

        user = UserAnalytics.objects.get(user=req.user)
        replies_given_by_user = user.replies_given.all()

        return render(req, 'blog/get_replies_given_per_user.html', {'replies_given': replies_given_by_user})

    else:
        next = req.GET.get('next', '/')
        return HttpResponseRedirect(reverse('blog:login') + "?next=" + next)

blog/templates/blog/comments.html
{% for comment in comments %}
    <div class="comment">
        <a href="#comment-1" class="comment-border-link">
            <span class="sr-only">Jump to comment-1</span>
        </a>
        {% if not comment.comment.isDeleted %}

            <!-- Comment heading start -->
            <div class="comment-heading">

                <!-- Comment voting start -->
                <div class="comment-voting">

                    {% if comment.liked %}
                        <a class="liked" href="{% url 'blog:set_comment_like' comment.comment.comment_id %}">
                            <span aria-hidden="true" class="ligature">&#9650;</span>
                            <span class="sr-only">Vote up</span>
                        </a>
                    {% else %}

                        <a href="{% url 'blog:set_comment_like' comment.comment.comment_id %}">
                            <span aria-hidden="true" class="ligature">&#9650;</span>
                            <span class="sr-only">Vote up</span>
                        </a>

                    {% endif %}

                    {% if comment.disliked %}
                        <a class="disliked" href="{% url 'blog:set_comment_dislike' comment.comment.comment_id %}">
                            <span aria-hidden="true" class="ligature">&#9660;</span>
                            <span class="sr-only">Vote down</span>
                        </a>
                    {% else %}
                        <a href="{% url 'blog:set_comment_dislike' comment.comment.comment_id %}">
                            <span aria-hidden="true" class="ligature">&#9660;</span>
                            <span class="sr-only">Vote down</span>
                        </a>
                    {% endif %}
                    
                </div>
                <!-- Comment voting end -->

                <!-- Comment info (author, # of votes, time added) start -->
                <div class="comment-info">

                        <div class="author-pin">
                            
                            <a href="{% url 'blog:get_blogs' comment.comment.comment_user.id %}" class="comment-author">
                                <span class="comment-author">
                                    {{comment.comment.comment_user.first_name}}
                                </span>
                                
                                
                            </a>
                            <span class="pin-control">
                                {% if blog.user.id == request.user.id %}
                                    {% if comment.comment.is_pinned %}
                                        <a href="{% url 'blog:pin_comment' comment.comment.comment_id %}" class="pin-comment"><i class="bi-pin-fill"></i></a>
                                    {% else %}
                                        <a href="{% url 'blog:pin_comment' comment.comment.comment_id %}" class="pin-comment"><i class="bi-pin"></i></a>
                                    {% endif %}

                                {% elif comment.comment.is_pinned %}
                                    <span class="pin-comment"><i class="bi-pin-fill"></i></span>
                                {% endif %}
                            </span>

                            
                        </div>

                    <p>
                        {{ comment.comment.noOfLikes }} Likes • {{ comment.comment.noOfDisLikes}} Dislikes• {{ comment.comment.creation_timestamp }}
                    </p>
                </div>
                <!-- Comment info (author, # of votes, time added) end -->
            </div>
            <!-- Comment heading end -->

            <!-- Comment body start -->
            <div class="comment-body">
                <p>
                {{comment.comment.body}}
                </p>
                <span class="controls">

                    <span class="update-delete-controls">
                        {% if request.user.id == comment.comment.comment_user.id %}

                            {% if comment.comment.isRoot %}
                                <a href="{% url 'blog:update_comment' blog.blogid comment.comment.comment_id %}" class="comment-control btn btn-warning"><i class="bi-pencil-square"></i></a>
                                <a href="{% url 'blog:delete_comment' blog.blogid comment.comment.comment_id %}" class="comment-control btn btn-danger"><i class="bi-trash-fill"></i></a>
                            {% else %}
                                <a href="{% url 'blog:update_reply' blog.blogid comment.root_comment_id comment.comment.comment_id %}" class="comment-control btn btn-warning"><i class="bi-pencil-square"></i></a>
                                <a href="{% url 'blog:delete_reply' blog.blogid comment.root_comment_id comment.comment.comment_id %}" class="comment-control btn btn-danger"><i class="bi-trash-fill"></i></a>
                            {% endif %}
                        {% endif %}
                    
                    </span>
                    
                    {% if request.user.id != comment.comment.comment_user.id %}
                        <span class="reply-control">
                            <a href="{% url 'blog:add_reply' blog.blogid comment.comment.comment_id %}" 
                                class="btn btn-warning comment-control">
                                    <i class="bi-reply-fill"></i>
                            </a>
                        </span>
                    {% endif %}
                </span>
            </div>
            
        {% else %}

            <!-- Comment heading start -->
            <div class="comment-heading">

                <!-- Comment voting end -->

                <!-- Comment info (author, # of votes, time added) start -->
                <div class="comment-info">
                    <a href="#" class="comment-author">{{comment.comment.comment_user.first_name}}</a>
                    <p>
                        {{ "# of votes" }} • {{ comment.comment.creation_timestamp }}
                    </p>
                </div>
                <!-- Comment info (author, # of votes, time added) end -->
            </div>
            <!-- Comment heading end -->

            <!-- Comment body start -->
            <div class="comment-body">
                <p>Comment has been deleted</p>
                <span class="controls">

                    <span class="update-delete-controls">
                        {% if request.user.id == comment.comment.comment_user.id %}
                            <a 
                                href="{% url 'blog:delete_reply' blog.blogid comment.root_comment_id comment.comment.comment_id %}" 
                                class="comment-control btn btn-success">
                                <i class="bi-arrow-counterclockwise"></i>
                            </a>                
                        {% endif %}
                    
                    </span>
                    

                </span>
            </div>

        {% endif %}
            
        <!-- Replies start -->

        {% if comment.replies|length %}
            <div class="replies">
                {% include "blog/comments.html" with comments=comment.replies blog=blog %}
            </div>
        {% endif %}
        <!-- Replies end -->

    </div>

{% endfor %}

blog/templates/blog/create_tags.html
{% extends 'blog/base.html' %}

{% block title %}

    Create a new Tag

{% endblock title %}


{% block body %}

    <form action="{% url 'blog:create_tag' %}" method="post">
        {% csrf_token %}
        {{ form }}

        <input type="submit" value="Create Tag" class="btn btn-primary tag-submit-btn">
    </form>

{% endblock body %}

blog/templates/blog/dashboard.html
{% extends 'blog/base.html' %}

{% block title%}DashBoard{%endblock%}


{% block body%}
<h1>Welcome, {{ user.first_name }}.</h1>

{% if blogs|length == 0%}
    <h1>You don't have any blogs. Please create one <a href="{% url 'blog:create_blog' %}">Click Here</a></h1>
{% else %}
    <h1>Here are your blogs</h1>
    <table class="table">
        <tr>
            <th>Title</th>
            <th>Views</th>
            <th>Likes</th>
            <th>Dis-Likes</th>
            <th>Comments</th>
            <th>Creation TimeStamp</th>
            <th>Modified TimeStamp</th>
            <th>Visible</th>
            <th>No. of tags</th>
            <th>Tags</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        {% for blog in blogs %}
            <tr>
                <td><a href="/home/{{blog.blogid}}" target="_blank">{{blog.title}}</a></td>
                <td>{{blog.numberOfViews}}</td>
                <td>{{blog.noOfLikes}}</td>
                <td>{{blog.noOfDisLikes}}</td>
                <td>{{blog.noOfComments}}</td>
                <td>{{blog.creation_timestamp}}</td>
                <td>{{blog.modified_timestamp}}</td>
                <td>{{blog.isVisible}}</td>
                <td>{{blog.noOfTags}}</td>
                <td>
                    <ul class="tags">
                        {% for tag in blog.tags.all %}
                            <li class="tag">{{tag}}</li>
                        {% endfor %}
                    </ul>
                </td>
                <td><a href="{% url 'blog:update_blog' blog.blogid %}" class="blog-control btn btn-warning"><i class="bi-pencil-square"></i></a></td>
                <td><a href="{% url 'blog:delete_blog' blog.blogid %}" class="blog-control btn btn-danger"><i class="bi-trash-fill"></i></a></td>
            </tr>
        {% endfor %}
    
    </table>

    <a href="{% url 'blog:create_blog'%}" class="btn btn-primary">Create a new Blog</a>

{% endif %}


{% if tags|length %}
    
    <h1>Here are your tags</h1>
    <table class="table">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        {% for tag in tags %}
            <tr>
                <td>{{tag.tagid}}</td>
                <td>{{tag.tag_name}}</td>
                <td><a href="/home/{{tag.tagid}}/update/tag" class="tag-control btn btn-warning"><i class="bi-pencil-square"></i></a></td>
                <td><a href="/home/{{tag.tagid}}/delete/tag" class="tag-control btn btn-danger"><i class="bi-trash-fill"></i></a></td>
            </tr>
        {% endfor %}
    
    </table>

    <a href="{% url 'blog:create_tag'%}" class="btn btn-primary">Create a new tag</a>



{% else %}
    <h1>You don't have any tags. Please create one <a href="{% url 'blog:create_tag' %}">Click Here</a></h1>
{% endif %}

{%endblock%}

blog/templates/blog/get_comment_dislikes_per_user.html
{% extends 'blog/base.html' %}

{% block title %}
    Comment's disliked
{% endblock title %}

{% block body %}
    {% if comment_dislikes|length %}

        <h1>Comment's disliked by you</h1>
        <table class="table">
            <tr>
                <th>Comment Body</th>
                <th>Comment By</th>
                <th>Blog</th>
                <th>Blog Author</th>
                <th>Like</th>
                <th>Dislike</th>
            </tr>
            {% for comment_dislike in comment_dislikes %}
                <tr>
                    <td>{{comment_dislike.body}}</td>
                    <td>
                        {{comment_dislike.comment_user.first_name}}
                        {% if request.user == comment_dislike.comment_user %}
                            (You)
                        {% endif %}
                    </td>
                    <td><a href="{% url 'blog:get_blog' comment_dislike.blog.blogid %}" target="_blank">{{comment_dislike.blog.title}}</a></td>
                    <td>
                        {{comment_dislike.blog.user.first_name}}
                        {% if request.user == comment_dislike.blog.user %}
                            (You)
                        {% endif %}

                    </td>
                    <td><a href="{% url 'blog:set_comment_like' comment_dislike.comment_id %}?next={{request.path}}" class="btn btn-outline-primary">Like</a></td>
                    <td><a href="{% url 'blog:set_comment_dislike' comment_dislike.comment_id %}?next={{request.path}}" class="btn btn-primary">Dislike</a></td>
                </tr>
            {% endfor %}
        
        </table>
    {% else %}
        <h1>Sorry, you have not disliked any comments/replies till date.</h1>
    {% endif %}

{% endblock body %}

blog/templates/blog/get_comments_given_per_user.html
{% extends 'blog/base.html' %}

{% block title %}
    Comments given
{% endblock title %}

{% block body %}
    {% if comments_given|length %}

        <h1>Comments given by you</h1>
        <table class="table">
            <tr>
                <th>Comment Body</th>
                <th>Total Likes</th>
                <th>Total Dislikes</th>
                <th>Blog</th>
                <th>Blog Author</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
            {% for comment_given in comments_given %}
                <tr>
                    <td>{{comment_given.body}}</td>
                    <td>{{comment_given.noOfLikes}}</td>
                    <td>{{comment_given.noOfDisLikes}}</td>
                    <td><a href="{% url 'blog:get_blog' comment_given.blog.blogid %}" target="_blank">{{comment_given.blog.title}}</a></td>
                    <td>
                        {{comment_given.blog.user.first_name}}
                        {% if request.user == comment_given.blog.user %}
                            (You)
                        {% endif %}

                    </td>

                    <td><a href="{% url 'blog:update_comment' comment_given.blog.blogid comment_given.comment_id %}?next={{request.path}}" class="blog-control btn btn-warning"><i class="bi-pencil-square"></i></a></td>
                    <td><a href="{% url 'blog:delete_comment' comment_given.blog.blogid comment_given.comment_id %}?next={{request.path}}" class="blog-control btn btn-danger"><i class="bi-trash-fill"></i></a></td>
                </tr>
            {% endfor %}
        
        </table>
    {% else %}
        <h1>Sorry, you have not given any comments till date.</h1>
    {% endif %}

{% endblock body %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block title%} Home {% endblock %}

{% block body %}
    {% if users|length == 0 %}
        <h1>There are no users in the system</h1>
        <h4>Create some by <a href="{% url 'blog:signup' %}">Signing Up</a></h4>
    {% else %}
        <ul>
            {% for user in users %}
                <li><a href="{{user.id}}/blogs">{{ user.first_name}}</a></li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}